// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOfQWjO0ye8wC-lDQWLrTlKHA9yWPLX_o',
    appId: '1:238049355336:web:e225c84e452befd51c9a7d',
    messagingSenderId: '238049355336',
    projectId: 'ktr-event-project',
    authDomain: 'ktr-event-project.firebaseapp.com',
    storageBucket: 'ktr-event-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANxsFvKtiTW93BNfQpAQ2gKCDeFoWMukk',
    appId: '1:238049355336:android:ba09d659ad481ebb1c9a7d',
    messagingSenderId: '238049355336',
    projectId: 'ktr-event-project',
    storageBucket: 'ktr-event-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD34GkA4eKPVwVHeFlsOt7kZOVm-SdjQSc',
    appId: '1:238049355336:ios:98a9509a74942ec71c9a7d',
    messagingSenderId: '238049355336',
    projectId: 'ktr-event-project',
    storageBucket: 'ktr-event-project.firebasestorage.app',
    iosBundleId: 'com.utm.razakevent.razakevent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD34GkA4eKPVwVHeFlsOt7kZOVm-SdjQSc',
    appId: '1:238049355336:ios:98a9509a74942ec71c9a7d',
    messagingSenderId: '238049355336',
    projectId: 'ktr-event-project',
    storageBucket: 'ktr-event-project.firebasestorage.app',
    iosBundleId: 'com.utm.razakevent.razakevent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOfQWjO0ye8wC-lDQWLrTlKHA9yWPLX_o',
    appId: '1:238049355336:web:9f89841163b0b1671c9a7d',
    messagingSenderId: '238049355336',
    projectId: 'ktr-event-project',
    authDomain: 'ktr-event-project.firebaseapp.com',
    storageBucket: 'ktr-event-project.firebasestorage.app',
  );
}
